


export const metadata = {
    title: "My Wishlist",
    description: "Generated by create next app",
  };

export default function RootLayout({ children }) {
    
    return(
        <>
         {children}
         </>
       
    )
}